In [1]:
from PIL import Image
import numpy as np
import pandas as pd
from sklearn.svm import SVC
import cv2
import glob
import math
import os
import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score
from matplotlib import pyplot as plt

In [3]:
def shi_tomasi_corner_detection(image,corners=50,Quality_Level=0.01,Euclidean_Distance=10):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    corners = cv2.goodFeaturesToTrack(gray,corners,Quality_Level,Euclidean_Distance)
    corners = np.int0(corners)
    clr=(0,0,255)
    for i in corners:
        x,y = i.ravel()
        cv2.circle(image,(x,y),3,clr,-1)
    return image

In [4]:
# Append Pothole images
number = 1
table = []
pot = 343

for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/trial/pothole/" + str(number) + ".jpg"
    im = Image.open(var)
    im = im.resize((300, 300))
    data = np.array(im)
    flattened = data.flatten()
    table.append(flattened)
    number = number + 1

In [5]:
# Append Non Pothole images
number = 1
npot = 355

for i in range(npot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/trial/plain/" + str(number) + ".jpg"
    im = Image.open(var)
    im = im.resize((300, 300))
    data = np.array(im)
    flattened = data.flatten()
    table.append(flattened)
    number = number + 1

In [6]:
y = []
for i in range(pot):
    y.append(1)
for i in range(npot):
    y.append(0)

In [7]:
svc=SVC(probability=True)
svc.fit(table,y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [8]:
number = 1
test = []
pot = 8 

for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Pothole/" + str(number) + ".jpg"
    im = Image.open(var)
    im = im.resize((300, 300))
    data = np.array(im)
    flattened = data.flatten()
    test.append(flattened)
    number = number + 1


print(svc.predict(test))

[1 1 1 1 1 1 0 0]


In [9]:
number = 1
test = []
npot = 8 

for i in range(npot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Plain/" + str(number) + ".jpg"
    im = Image.open(var)
    im = im.resize((300, 300))
    data = np.array(im)
    flattened = data.flatten()
    test.append(flattened)
    number = number + 1


print(svc.predict(test))

[1 1 1 1 0 0 0 0]


In [10]:
#input of pothole images with corner detection
number = 1
train = []
pot = 343

for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/trial/pothole/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    data = np.array(corner1)
    flattened = data.flatten()
    train.append(flattened)
    number = number + 1    

In [11]:
#input of plain images with corner detection
number = 1
npot = 355

for i in range(npot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/trial/plain/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    data = np.array(corner1)
    flattened = data.flatten()
    train.append(flattened)
    number = number + 1

In [12]:
meh=SVC(probability=True)
meh.fit(train,y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [13]:
#output with corner
number = 1
test = []
pot = 8 

for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Pothole/" + str(number) + ".jpg"
    im = Image.open(var)
    im = im.resize((300, 300))
    data = np.array(im)
    flattened = data.flatten()
    test.append(flattened)
    number = number + 1


print(meh.predict(test))

[1 1 1 1 1 1 0 0]
