In [1]:
from PIL import Image
import numpy as np
import pandas as pd
from sklearn.svm import SVC

In [28]:
# Append Pothole images
number = 1
table = []
pot = 357

for i in range(pot):
    var = "trial/pothole/" + str(number) + ".jpg"
    im = Image.open(var)
#    im = im.resize(300, 300)
    data = np.array(im)
    flattened = data.flatten()
    table.append(flattened)
    number = number + 1

FileNotFoundError: [Errno 2] No such file or directory: 'trial/pothole/5.jpg'

In [21]:
table

[array([203, 196, 188, ..., 110, 101,  96], dtype=uint8),
 array([82, 61, 68, ..., 33, 22, 26], dtype=uint8),
 array([111, 111, 113, ..., 175, 174, 172], dtype=uint8),
 array([ 3,  3,  5, ..., 58, 59, 64], dtype=uint8),
 array([71, 71, 69, ..., 64, 64, 64], dtype=uint8),
 array([46, 28, 16, ...,  8,  3,  0], dtype=uint8),
 array([39, 47, 32, ..., 88, 86, 87], dtype=uint8),
 array([161, 163, 184, ..., 120, 118, 121], dtype=uint8),
 array([ 7, 27, 36, ..., 34, 34, 34], dtype=uint8),
 array([13, 13, 15, ...,  1,  2,  4], dtype=uint8),
 array([ 69,  73,  82, ..., 108, 103, 100], dtype=uint8),
 array([209, 209, 219, ..., 143, 129, 116], dtype=uint8),
 array([148, 145, 140, ...,  76,  76,  78], dtype=uint8),
 array([ 82,  78,  69, ..., 183, 184, 178], dtype=uint8),
 array([198, 198, 196, ..., 182, 173, 164], dtype=uint8),
 array([171, 204, 195, ...,  80,  80, 255], dtype=uint8),
 array([107, 100, 107, ..., 166, 168, 167], dtype=uint8),
 array([ 52,  56,  57, ..., 147, 145, 132], dtype=uint8)

In [11]:
# Append Non Pothole images
number = 1
table = []
pot = 367

for i in range(pot):
    var = "train/Plain/" + str(number) + ".jpg"
    im = Image.open(var)
    im = im.resize(300, 300)
    data = np.array(im)
    flattened = data.flatten()
    table.append(flattened)
    number = number + 1

TypeError: can only concatenate str (not "int") to str

In [ ]:
y = []
for i in range(pot):
    y.append(1)
for i in range(npot):
    y.append(0)

In [15]:
svc=SVC(probability=True)
svc.fit(table,y)

/home/harsh/.local/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=True, random_state=None,
  shrinking=True, tol=0.001, verbose=False)