In [56]:
from PIL import Image
import numpy as np
import pandas as pd
from sklearn.svm import SVC
import cv2
import glob
import math
import os
import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score
from matplotlib import pyplot as plt
import time

In [57]:
def image_to_feature_vector(image, size=(300, 300)):
    return cv2.resize(image, size)

In [58]:
def shi_tomasi_corner_detection(image,corners=50,Quality_Level=0.01,Euclidean_Distance=10):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    corners = cv2.goodFeaturesToTrack(gray,corners,Quality_Level,Euclidean_Distance)
    corners = np.int0(corners)
    clr=(0,0,255)
    for i in corners:
        x,y = i.ravel()
        cv2.circle(image,(x,y),3,clr,-1)
    return image

In [59]:
#input of pothole images with corner detection
number = 1
train = []
pot = 343

for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/trial/pothole/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    
    edges = cv2.Canny(corner,100,200)
    
    data = np.array(corner1)
    data2 = np.array(edges)
    
    flattened = data.flatten()
    flattened2 = data2.flatten()
    temp=np.concatenate([flattened,flattened2])
    
    train.append(temp)
    number = number + 1  

In [60]:
start_time = time.time()
#input of plain images with corner detection
number = 1
npot = 355

for i in range(npot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/trial/plain/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    
    edges = cv2.Canny(corner,100,200)
    
    data = np.array(corner1)
    data2 = np.array(edges)
    
    flattened = data.flatten()
    flattened2 = data2.flatten()
    temp=np.concatenate([flattened,flattened2])
    
    train.append(temp)
    number = number + 1 
print(time.time() - start_time)

16.069234371185303


In [61]:
y = []
for i in range(pot):
    y.append(1)
for i in range(npot):
    y.append(0)

In [62]:
start_time = time.time()
meh=SVC(probability=True)
meh.fit(train,y)
print(time.time() - start_time)

1553.6264653205872


In [50]:
#output of pothole images with corner detection
number = 1
pot = 8
test=[]
for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Pothole/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    
    edges = cv2.Canny(corner,100,200)
    
    data = np.array(corner1)
    data2 = np.array(edges)
    
    flattened = data.flatten()
    flattened2 = data2.flatten()
    temp=np.concatenate([flattened,flattened2])
    
    test.append(temp)
    number = number + 1 

print(meh.predict(test))

[1 0 1 1 1 1 0 0]


In [51]:
#output of pothole images with corner detection
number = 1
pot = 8
test=[]
for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Plain/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    
    edges = cv2.Canny(corner,100,200)
    
    data = np.array(corner1)
    data2 = np.array(edges)
    
    flattened = data.flatten()
    flattened2 = data2.flatten()
    temp=np.concatenate([flattened,flattened2])
    
    test.append(temp)
    number = number + 1 

print(meh.predict(test))

[1 0 0 1 0 0 0 0]


In [12]:
#output of pothole images with corner detection
number = 1
test = []
pot = 8

for i in range(pot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Pothole/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    
    data = np.array(corner1)
    flattened = data.flatten()
    test.append(flattened)
    number = number + 1 

print(meh.predict(test))

[1 1 1 1 1 1 0 0]


In [13]:
#output of pothole images with corner detection
number = 1
test = []
npot = 8

for i in range(npot):
    var = "C:/Users/subhashis sengupta/Desktop/pothole images/My Dataset/test/Plain/" + str(number) + ".jpg"
    pic = cv2.imread(var)
    corner = image_to_feature_vector(pic)
    corner1 = shi_tomasi_corner_detection(corner)
    cv2.imshow('og',corner)
    cv2.imshow('canny',corner1)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    data = np.array(corner1)
    flattened = data.flatten()
    test.append(flattened)
    number = number + 1 

print(meh.predict(test))

[1 1 1 1 0 0 0 0]
